ArcadeRatingCard
TiOlabs/SportZi-FrontEnd pull request #3
Opened 2024-01-31 20:49 UTC by Bhathiya2001

1st creat need to dev

2024-02-11 15:45 UTC, spynav requested changes

2024-02-11 15:45 UTC, spynav commented on src/components/arcadeRatingCard.tsx
> +
remove this space

2024-02-11 15:45 UTC, spynav commented on src/components/arcadeRatingCard.tsx
> +
remove this space

2024-02-11 15:45 UTC, spynav commented on src/components/arcadeRatingCard.tsx
> +
remove these space lines

2024-02-11 15:45 UTC, spynav commented on src/components/arcadeRatingCard.tsx
> +
remove this line

2024-02-11 15:45 UTC, spynav commented on src/components/navbar.tsx
> +
remove space

2024-02-11 15:45 UTC, spynav commented on src/pages/home/arcadeRatingCardSection.tsx
> +
remove these space lines

2024-02-11 16:30 UTC, spynav commented on src/components/navbar.tsx
> -    return (
use arrow function

2024-02-11 16:40 UTC, Bhathiya2001 commented on src/components/navbar.tsx
> -    return (
i changed this leader
fk u

2024-02-11 16:44 UTC, spynav approved these changes

2024-02-12 22:45 UTC, spynav approved these changes

2024-02-12 22:47 UTC, merged